### ISSUE TITLE
Mieux calibrer le rectangle et ses touches

### ISSUE THREAD

**Issue by ipante** [Nixoux/Save-the-Forest#11]
Cf. dépassement à droite.

<img width="393" alt="Capture d’écran 2023-08-20 à 11 19 16" src="https://github.com/Nixoux/Save-the-Forest/assets/1324037/f915f920-c032-4347-be52-c77a46fa33c1">

**Comment by Nixoux** [comment]
Modification faite, devrait être en ordre:

![TitleScreenGameFinal](https://github.com/Nixoux/Save-the-Forest/assets/32510810/1c57408a-384c-4600-ad13-217d51313455)
