### ISSUE TITLE
Distinguer les différents boss

### ISSUE THREAD

**Issue by ipante** [Nixoux/Save-the-Forest#15]
Par une teinte de vert (utiliser de nouveau les fonctions pour teinter le sprite)

**Comment by Nixoux** [comment]
Finalement, j'ai pris le temps de faire un triple recolor. Aussi j'ai précisé les feuilles à leurs pieds. J'ai intensifié le jaune qui devient de plus en plus vert (de manière progressive) pour atteindre la boss finale (la plus verte de toute).

Originale:
![Untitled 13 2](https://github.com/Nixoux/Save-the-Forest/assets/32510810/f351373b-30d3-4c63-98bd-ad0154e6c355)

Les nouvelles:

![Untitled 13 2 2](https://github.com/Nixoux/Save-the-Forest/assets/32510810/d1e11f40-d16a-4c2e-aadb-6a1dedc21117)
![Untitled 13 2 2 2](https://github.com/Nixoux/Save-the-Forest/assets/32510810/a2dbb5c1-06e7-47c2-98a5-6f159ad54e5b)
![Untitled 13 2 3](https://github.com/Nixoux/Save-the-Forest/assets/32510810/18a88215-1019-4fbe-b7ab-5df33ba11f03)
