### ISSUE TITLE
Tir coloré ?

### ISSUE THREAD

**Issue by ipante** [Nixoux/Save-the-Forest#22]
Le tir noir est-il vraiment le plus heureux ? Avez-vous essayé du violet foncé ?

**Comment by Nixoux** [comment]
J'ai vite fait dessiné et intégré un sprite pour le tir. 
![purple](https://github.com/Nixoux/Save-the-Forest/assets/32510810/0eeb0ccf-bbe9-43d7-ad89-4dc2a52dec4e)
