### ISSUE TITLE
Modifier le background à chaque blessure

### ISSUE THREAD

**Issue by ipante** [Nixoux/Save-the-Forest#9]
Soit tirer vers le rouge (pour appeler la défaite) soit vers le vert (couleur de l'ambroisie) soit vers le noir (couleur de la mort). La fonction tint vous permet de le faire très facilement.

**Comment by Nixoux** [comment]
Je n'ai pas réussi à teinter le background avec tint(), la fonction ne se trouve pas dans la doc kaboom. J'ai essayé de passer par des shaders et finalement j'ai trouvé une solution plus simple en un rectangle de couleur à qui on modifie les valeurs de couleurs et opacités.

**Comment by ipante** [comment]
Je l'avais fait sur The Spicy Interview : vous pouvez accéder à la propriété color d'un sprite et faire évoluer sa couleur, sans ajout de rectangle :

`fond.color.r += 2;`

Ma solution est visible en ligne 286 sur cette page : https://replit.com/@isaacpante/The-Spicy-Interview#scripts/main.js
